[package]
name = "avatar-rs"
version = "0.1.0"
edition = "2024"

[lib]
name = "avatar_rs"

[dependencies]
image = "0.25.5"
rand = "0.9.0"

[dev-dependencies]
criterion = "0.5.1"

# [[bench]]
# name = "benchmark"
# harness = false

[[bench]]
name = "icon_benchmark"
harness = false
